package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	root := "data/sequences/mRNA"
	files, _ := filepath.Glob(filepath.Join(root, "*.fasta"))

	for _, file := range files {
		name := strings.TrimSuffix(filepath.Base(file), "_mRNA.fasta")
		fmt.Printf("// Autogenerated for %s\n", name)

		seq := parseFasta(file)
		fmt.Printf(`var %s_mRNA = molecular_types.Exerkine{
	Name: "%s",
	Category: "mRNA",
	TissueSources: []string{"Skeletal muscle"},
	BiologicalFunc: "Exercise-induced mRNA expression",
	Sequence: `+"`%s`"+`,
	PDBID: "",
	Receptors: nil,
}
`, name, name, seq)
	}
}

func parseFasta(path string) string {
	f, _ := os.Open(path)
	defer f.Close()

	scanner := bufio.NewScanner(f)
	var seq strings.Builder

	for scanner.Scan() {
		line := scanner.Text()
		if strings.HasPrefix(line, ">") {
			continue
		}
		seq.WriteString(line)
	}
	return seq.String()
}
